# A study on VLM-driven ceiling fan airflow analysis w/ Unity
#
# Dragonwing IQ-9075 EVK
#
# By Kutluhan Aktar


import os
import cv2
import time
import numpy as np
import subprocess
import json
import socket
import base64
from threading import Thread
import requests
from flask import Flask, render_template, jsonify, request
from rplidar import RPLidar

class unity_lidar_vlm_data_hub():
    def __init__(self):
        # Declare the necessary RPLIDAR A1 lidar information, including the port the Unity application listening to obtain the generated lidar points. 
        self.rplidar = {"port": "/dev/ttyUSB0", "udp_port": 5005, "active": True}
        # Declare the necessary Unity application information, including its lightweight HTTP server for frame generation.
        unity_ip = "0.0.0.0"
        self.unity = {"ip": unity_ip, "get_frame_api": f"http://{unity_ip}:8080/get_video_frames/"}
        # Declare the API endpoint for the Qualcomm LLM/VLM Docker container.
        self.qualcomm_vlm_port = 9001
        self.qualcomm_vlm_api = f"http://localhost:{self.qualcomm_vlm_port}/v1/chat/completions"
        
    def lidar_point_generator(self):
        # Obtain the scan points continuously generated by the RPLIDAR A1.
        try:
            lidar = RPLidar(self.rplidar["port"])
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            print("RPLIDAR A1 streaming data to {}:{}...".format(self.unity["ip"], self.rplidar["udp_port"]))
            # Modify the scan points and pass them to the associated WebSocket.
            for scan in lidar.iter_scans():
                if not self.rplidar["active"]:
                    break
                points = [{"a": round(deg, 2), "d": round(dist, 2)} for _, deg, dist in scan]
                payload = json.dumps({"pts": points}).encode('utf-8')
                sock.sendto(payload, (self.unity["ip"], self.rplidar["udp_port"]))
        # Debugging and stopping the point generation.        
        except Exception as e:
            print(f"[RPLIDAR A1 ERROR] {e}")
        finally:
            print("[RPLIDAR A1] Stopping motor and disconnecting...")
            try:
                lidar.stop()
                lidar.stop_motor()
                lidar.disconnect()
            except:
                pass
    
    def run_point_generator(self):
        # Declare and initialize a Python thread for the continuous RPLIDAR A1 scan point generation.
        self.rplidar_thread = Thread(target=self.lidar_point_generator, daemon=True)
        self.rplidar_thread.start()
        
    def halt_point_generator(self):
        self.rplidar["active"] = False
        if hasattr(self, 'rplidar_thread'):
            self.rplidar_thread.join(timeout=3)       
 
    def obtain_frames_from_unity(self, frame_num, fps, save_as_video):
        # Make an HTTP GET request to the provided HTTP server by the Unity application to obtain consecutive video frames.
        params = {"count": frame_num, "fps": fps}
        response = requests.get(self.unity["get_frame_api"], params=params, timeout=240)
        # If successfull, pass the obtained frames in the JSON format.
        if response.status_code == 200:
            raw_frames = response.json().get("frames", [])
            print("Video frames obtained from the Unity app! Total: {}".format(len(raw_frames)))
            # Save the received frames as a video if enabled.
            if save_as_video and len(raw_frames) > 0:
                self.save_frames_as_video(raw_frames, fps)
            return [f"data:image/jpeg;base64,{f}" for f in raw_frames]
        else:
            raise Exception(f"Unity frame request failed: {response.status_code}")
        
    def save_frames_as_video(self, base64_frames, fps):
        # If requested, save the obtained frames as a video file for further inspection.
        try:
            timestamp = int(time.time())
            self.video_file_name = f"capture_{timestamp}.mp4"
            file_path = os.path.join("./static/unity_airflow_videos", self.video_file_name)
            temp_file_path = "./static/unity_airflow_videos/temp.mp4"
            # Decode the first frame to get dimensions.
            first_frame_bytes = base64.b64decode(base64_frames[0])
            first_frame_np = np.frombuffer(first_frame_bytes, dtype=np.uint8)
            first_img = cv2.imdecode(first_frame_np, cv2.IMREAD_COLOR)
            height, width, _ = first_img.shape
            # Initialize the VideoWriter class with the mp4v codec.
            fourcc = cv2.VideoWriter_fourcc(*'mp4v')
            video_writer = cv2.VideoWriter(temp_file_path, fourcc, fps, (width, height))
            # Process each received Unity application frame as a temporary file.
            for b64_str in base64_frames:
                img_bytes = base64.b64decode(b64_str)
                img_np = np.frombuffer(img_bytes, dtype=np.uint8)
                img = cv2.imdecode(img_np, cv2.IMREAD_COLOR)
                if img is not None:
                    video_writer.write(img)
            # Complete the temporary file saving process.
            video_writer.release()
            # Convert the saved temporary file in the mp4v codec to the H264 codec in order to make it browser-friendly.
            cmd = ['ffmpeg', '-y', '-i', temp_file_path, '-vcodec', 'libx264', '-pix_fmt', 'yuv420p', file_path]
            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            # Remove the temporary file.
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)           
            print(f"Unity airflow analysis video saved successfully: {file_path}")
        except Exception as e:
            print(f"Failed to save video: {e}")

    def vlm_airflow_analysis(self, prompt, vlm_model,  target_frame):
        # Request frames from the Unity application.
        frames = self.obtain_frames_from_unity(frame_num=16, fps=1, save_as_video=True)
        # Generate the VLM input with the obtained Unity frames.
        vlm_input = [{"type": "text", "text": prompt}]
        # Only pass the requested frame [1 - 16] to avoid model context buffer overflow, which is 2048.
        vlm_input.append({
            "type": "image_url",
            "image_url": {"url": frames[target_frame-1]}
        })
        payload = {
            "model": vlm_model,
            "messages": [{"role": "user", "content": vlm_input}]
        }
        # Make an HTTP POST request to the provided Qualcomm Docker container API.
        response = requests.post(self.qualcomm_vlm_api, json=payload, timeout=240)
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
        else:
            raise Exception(f"Model endpoint returned {response.status_code}: {response.text}")
 
    def flask_app_config(self, app):
        # Integrate the custom Flask app to this class.
        @app.route('/')
        def home():
            return render_template('index.html', unity_ip=self.unity["ip"])
        @app.route('/api/analyze', methods=['POST'])
        def trigger_analysis():
            data = request.get_json() or {}
            inference_info = data.get('inference_info')
            try:
                result = self.vlm_airflow_analysis(inference_info["prompt"], inference_info["model"], inference_info["selected_frame"])
                return jsonify({"status": "success", "result": result, "video_file_name": self.video_file_name})
            except Exception as e:
                return jsonify({"status": "error", "message": str(e)}), 500        
            
# Declare the Flask application, which will serve as the VLM user inferface on the Bluetooth-enabled Android application.
flask_app = Flask(__name__)            
        
# Define the unity_lidar_vlm_data_hub class object.        
unity_lidar_vlm_data_hub_obj = unity_lidar_vlm_data_hub()

# Integrate the class object to the given Flask application.
unity_lidar_vlm_data_hub_obj.flask_app_config(flask_app)

# Main thread fo VLM-based airflow analysis on Unity application frames.
if __name__ == "__main__":
    # Start the RPLIDAR A1 scan point generator.
    unity_lidar_vlm_data_hub_obj.run_point_generator()
    # Execute the given Flask app and halt the point generator once the app stopped working.
    try:
        flask_app.run(host='0.0.0.0', port=5000, debug=False)
    finally:
        unity_lidar_vlm_data_hub_obj.halt_point_generator()
        